[package]
name = "habitat-sup-client"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
workspace = "../../"

[dependencies]
futures = { version = "*" }
habitat-sup-protocol = { path = "../sup-protocol", default-features = false }
habitat_common = { path = "../common" }
log = "*"
# Must use fork see https://github.com/habitat-sh/habitat/issues/7270
prost = { git = "https://github.com/dingelish/prost" }
termcolor = "*"
tokio = { version = "*", features = ["full"] }
tokio-util = { version = "*", features = ["full"] }
