[package]
name = "hab"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
build = "../build-habitat.rs"
workspace = "../../"

[[bin]]
name = "hab"
doc = false

[dependencies]
# Can we keep these alphabetized? We're not savages.
base64 = "*"
bitflags = "*"
chrono = {version = "*", features = ["serde"]}
ctrlc = "*"
dirs = "*"
env_logger = "*"
flate2 = "*"
futures = { version = "*" }
glob = "*"
habitat_api_client = { path = "../builder-api-client" }
habitat_common = { path = "../common" }
habitat_core = { path = "../core" }
habitat-sup-client = { path = "../sup-client" }
habitat-sup-protocol = { path = "../sup-protocol", default-features = false }
hab-common-derive = { path = "../common-derive" }
# We need to lock here since v0.30.0 bumps to a version of pest that fails to build on Windows.
handlebars = { version = "*", default-features = false }
lazy_static = "*"
libc = "*"
log = "0.4"
pbr = "*"
rants = { version = "0.6.1", git = "https://github.com/habitat-sh/rants.git", features = ["native-tls"] }
reqwest = { version = "*", features = ["blocking", "json", "stream"] }
retry = { git = "https://github.com/habitat-sh/retry", features = ["asynchronous"] }
rustls = "*"
same-file = "*"
serde = { version = "*", features = ["derive"] }
serde_json = { version = "*", features = [ "preserve_order" ] }
serde_yaml = "*"
tabwriter = "*"
tar = "*"
termcolor = "*"
thiserror = "*"
anyhow = { version = "*", features = ["backtrace"] }
tokio = { version = "*", features = ["full"] }
toml = { version = "*", features = [ "preserve_order" ] }
url = { version = "*", features = ["serde"] }
walkdir = "*"
rustls-webpki = { version = "*", features = ["alloc"] }
tempfile = "*"


clap_v4 = { version = "4", package = "clap", features = ["env", "derive", "string", "wrap_help"]}

clap_complete = "*"

[dependencies.uuid]
version = "*"
features = ["v4"]

[target.'cfg(windows)'.dependencies]
widestring = "*"
winapi = { version = "^0.3", features = ["winuser", "windef"] }
winreg = "*"

[features]
default = ["supported_targets"]
functional = []
supported_targets = ["habitat_core/supported_targets"]
aarch64-linux = ["habitat_core/aarch64-linux"]
