[package]
name = "habitat-sup-protocol"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
build = "./build.rs"
workspace = "../../"

[dependencies]
base64 = "*"
bytes = "*"
habitat_core = { path = "../core" }
lazy_static = "*"
log = "*"
# Must use fork due to this issue https://github.com/danburkert/prost/issues/242
prost = { git = "https://github.com/dingelish/prost" }
# Must use fork due to this issue https://github.com/danburkert/prost/issues/242
prost-derive = { git = "https://github.com/dingelish/prost" }
rand = "*"
serde = "*"
serde_derive = "*"
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.2", features = ["full"] }

[build-dependencies]
heck = "*"
# Must use fork due to this issue https://github.com/danburkert/prost/issues/242
prost = { git = "https://github.com/dingelish/prost" }
# Must use fork due to this issue https://github.com/danburkert/prost/issues/242
prost-build = { git = "https://github.com/dingelish/prost" }
# Must use fork due to this issue https://github.com/danburkert/prost/issues/242
prost-types = { git = "https://github.com/dingelish/prost" }
tempfile = "*"

[dev-dependencies]
tempfile = "*"
toml = "*"

[features]
default = ["protocols"]
protocols = []

