# cargo audit config file
# https://github.com/rustsec/rustsec/blob/main/cargo-audit/audit.toml.example
#
# All of the options which can be passed via CLI arguments can also be
# permanently specified in this file.

[advisories]
# JAH: The warnings below have been grandfathered dating to the start of our use
# JAH: of cargo audit so that they can be dealt with over time. At the bottom of
# JAH: this file is is a comment block stating what updating each crate would
# JAH: require and what parts of habitat are downstream dependents
#
# advisory IDs to ignore e.g. ["RUSTSEC-2019-0001", ...]
ignore = [
    "RUSTSEC-2021-0137", # Unmaintained: sodiumoxide
]
informational_warnings = [
    "notice",
    "unmaintained",
    "unsound",
] # warn for categories of informational advisories
severity_threshold = "none" # CVSS severity ("none", "low", "medium", "high", "critical")

# Advisory Database Configuration
[database]
path = ".cargo/advisory-db"                        # Path where advisory git repo will be cloned
url = "https://github.com/RustSec/advisory-db.git" # URL to git repo
fetch = true                                       # Perform a `git fetch` before auditing (default: true)
stale = false                                      # Allow stale advisory DB (i.e. no commits for 90 days, default: false)

# Output Configuration
[output]
deny = [
    "warnings",
    "unmaintained",
    "unsound",
    "yanked",
] # exit on error if these are found
format = "terminal" # "terminal" (human readable report) or "json"
quiet = false # Only print information on error
show_tree = true # Show inverse dependency trees along with advisories (default: true)

[yanked]
enabled = true      # Warn for yanked crates in Cargo.lock (default: true)
update_index = true # Auto-update the crates.io index (default: true)

#-------------------------------------------------------------------------------
# "RUSTSEC-2021-0137",    # Unmaintained: sodiumoxide
#-------------------------------------------------------------------------------
#
# Requires selection of replacement cryptography crate
#
# sodiumoxide 0.2.7
# └── habitat_core 0.0.0
#
