[package]
name = "habitat-launcher"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
workspace = "../../"

[[bin]]
name = "hab-launch"
path = "src/main.rs"
doc = false

[dependencies]
env_logger = "*"
habitat_common = { path = "../common" }
# JW TODO: core has external deps that we don't want, libarchive/libsodium. We should either
# put these things behind a feature flag so we can statically compile the launcher.
habitat_core = { path = "../core" }
habitat-launcher-protocol = { path = "../launcher-protocol" }
# As suggested by the name, this branch corresponds to
# https://github.com/servo/ipc-channel/pull/233, requesting to merge
# https://github.com/angelortiz1007/ipc-channel/tree/windows to master.
#
# This is currently the most up-to-date work for Windows compatibility.
ipc-channel = { git = "https://github.com/habitat-sh/ipc-channel", branch = "PR-233-angelortiz1007-windows" }
libc = "*"
log = "*"
prost = "*"
semver = "*"

[target.'cfg(windows)'.dependencies]
winapi =  { version = "*", features = ["tlhelp32"] }
