format_version = 1
file_descriptor = "Packages to sync acceptance from production after release"

# These are all packages that we officially produce in a release.

[[x86_64-linux]]
channel = "stable"
packages = [
  "chef/hab-launcher",
  "chef/hab",
  "chef/hab-sup",
  "chef/hab-studio",
  "chef/hab-plan-build",
  "chef/hab-backline",
  "chef/hab-pkg-export-container",
  "chef/hab-pkg-export-tar",
]

[[aarch64-linux]]
channel = "stable"
packages = [
  "chef/hab-launcher",
  "chef/hab",
  "chef/hab-sup",
  "chef/hab-studio",
  "chef/hab-plan-build",
  "chef/hab-backline",
  "chef/hab-pkg-export-container",
  "chef/hab-pkg-export-tar",
]

[[x86_64-windows]]
channel = "stable"
packages = [
  "chef/windows-service",
  "chef/hab-launcher",
  "chef/hab",
  "chef/hab-sup",
  "chef/hab-studio",
  "chef/hab-plan-build-ps1",
  "chef/hab-pkg-export-container",
  "chef/hab-pkg-export-tar"
]
