baseURL = "/"
languageCode = "en-us"
title = "Habitat Documentation"
theme = "docs-new"
enableGitInfo = true
pluralizeListTitles = false

disableKinds = false

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
		extensions = ["hardLineBreak"]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "friendly"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1


[params]
  enable_search = true
  robots = ''
  menuOrder = ["infra", "workstation", "habitat", "inspec", "automate", "legacy", "api", "extra"]

[taxonomies]
  category = "categories"
  tag = "tags"
  resource = "resources"

## Main Menu ##

[[menu.main]]
title = "Chef.io"
identifier = "chef"
url = "https://www.chef.io/"
weight = 10

[[menu.main]]
title = "Learn Chef"
identifier = "learn chef"
url = "https://learn.chef.io/"
weight = 20

[[menu.main]]
title = "Blog"
identifier = "blog"
url = "https://blog.chef.io/"
weight = 30

[[menu.main]]
title = "Community"
identifier = "community"
url = "https://community.chef.io/"
weight = 40

[[menu.main]]
title = "Training"
identifier = "training"
url = "https://training.chef.io/"
weight = 50

[[menu.main]]
title = "Download"
identifier = "download"
url = "https://downloads.chef.io/"
weight = 60

###
# Chef Habitat Menu ##
###

[[menu.habitat]]
title = "Chef Habitat"
identifier = "habitat"
weight = 10

[[menu.habitat]]
title = "Overview"
identifier = "overview"
weight = 20

  [[menu.habitat]]
  title = "Concepts"
  identifier = "overview/concepts"
  parent = "overview"
  weight = 100

[[menu.habitat]]
title = "Get Started"
identifier = "get_started"
weight = 30

[[menu.habitat]]
title = "Builder"
identifier = "builder"
weight = 40

[[menu.habitat]]
title = "Packages"
identifier = "packages"
weight = 50

[[menu.habitat]]
title = "Plans"
identifier = "plans"
weight = 60

[[menu.habitat]]
title = "Services"
identifier = "services"
weight = 70

[[menu.habitat]]
title = "Supervisors"
identifier = "supervisors"
weight = 80

[[menu.habitat]]
title = "Studio"
identifier = "studio"
url = "/studio"
weight = 90

[[menu.habitat]]
title = "Containers"
identifier = "containers"
weight = 110

[[menu.habitat]]
title = "Reference"
identifier = "reference"
weight = 120

  [[menu.habitat]]
  title = "Diagrams"
  identifier = "reference/diagrams"
  parent = "reference"


