baseURL = "/"
languageCode = "en-us"
title = "Chef Habitat Docs"
theme = "docs-new"
enableGitInfo = true
pluralizeListTitles = false


[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
		extensions = ["hardLineBreak"]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "friendly"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1


[params]
  enable_search = true
  robots = ''

[taxonomies]
  category = "categories"
  tag = "tags"
  resource = "resources"

## Main Menu ##

[[menu.main]]
title = "Chef.io"
identifier = "chef"
url = "https://www.chef.io/"
weight = 10

[[menu.main]]
title = "Learn Chef"
identifier = "learn chef"
url = "https://learn.chef.io/"
weight = 20

[[menu.main]]
title = "Blog"
identifier = "blog"
url = "https://blog.chef.io/"
weight = 30

[[menu.main]]
title = "Community"
identifier = "community"
url = "https://community.chef.io/"
weight = 40

[[menu.main]]
title = "Training"
identifier = "training"
url = "https://training.chef.io/"
weight = 50

[[menu.main]]
title = "Download"
identifier = "download"
url = "https://downloads.chef.io/"
weight = 60


## Docs Menu ##

[[menu.docs]]
title = "Chef Habitat"
identifier = "overview"
weight = 20

  [[menu.docs]]
  title = "Community"
  identifier = "community"
  parent = "overview"
  weight = 20

  [[menu.docs]]
  title = "Packages & Platforms"
  identifier = "packages_&_platforms"
  parent = "overview"
  weight = 30

  [[menu.docs]]
  title = "Licensing"
  identifier = "licensing"
  parent = "overview"
  weight = 50

[[menu.docs]]
title = "Available on GitHub"
identifier = "github"
url = "https://github.com/habitat.sh/habitat"
weight = 90

[[menu.docs]]
title = "Get Chef"
identifier = "get chef"
url = "https://www.chef.io/get-chef"
weight = 100

[[menu.docs]]
title = "Send Feedback"
identifier = "send feedback"
url = "/feedback/"
weight = 110

[[menu.docs]]
title = "Support"
identifier = "support"
url = "https://www.chef.io/support/"
weight = 120

[[menu.docs]]
title = "Archive"
identifier = "archive"
url = "https://docs-archive.chef.io/"
weight = 130
