[package]
name = "habitat_sup"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
build = "./build.rs"
workspace = "../../"

[lib]
name = "habitat_sup"

[[bin]]
name = "hab-sup"
path = "src/main.rs"
doc = false

[dependencies]
bytes = "*"
actix-web = { version = "*", default-features = false, features = [ "rust-tls" ] }
byteorder = "*"
clap = { version = "*", features = [ "suggestions", "color", "unstable" ] }
cpu-time = "*"
# futures 0.1 is needed because actix-web has not yet upgraded to futures 0.3.
# We must hardcode the new version of futures here because we also depened on futures 0.1
# See https://github.com/habitat-sh/habitat/issues/7271
futures = { version = "0.3.1" }
futures01 = { package = "futures", version = "0.1" }
glob = "*"
hab = { path = "../hab" }
habitat_butterfly = { path = "../butterfly", default-features = false }
habitat_common = { path = "../common" }
habitat_core = { path = "../core" }
habitat_api_client = { path = "../builder-api-client" }
habitat_http_client = { path = "../http-client" }
habitat-launcher-client = { path = "../launcher-client" }
habitat-sup-protocol = { path = "../sup-protocol", default-features = false }
lazy_static = "*"
libc = "*"
log = "*"
log4rs = "*"
nats = { git = "https://github.com/habitat-sh/rust-nats", rev = "a4c24be66fc54c0038af383b6df18d2ed0b5f376" }
notify = "*"
num_cpus = "*"
parking_lot = "*"
prometheus = "*"
# Must use fork see https://github.com/habitat-sh/habitat/issues/7270
prost = { git = "https://github.com/dingelish/prost" }
# Must use fork see https://github.com/habitat-sh/habitat/issues/7270
prost-derive = { git = "https://github.com/dingelish/prost" }
# Must use fork see https://github.com/habitat-sh/habitat/issues/7270
prost-types = { git = "https://github.com/dingelish/prost" }
rand = "*"
regex = "*"
rustls = "*"
serde = { version = "*", features = ["rc"] }
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
serde-transcode = "*"
state = "*"
tempfile = "*"
termcolor = "*"
time = "*"
toml = { version = "*", default-features = false }
tokio = { version = "*", features = ["full"] }
tokio-util = { version = "*", features = ["full"] }
url = "*"
valico = "*"

[target.'cfg(target_os = "linux")'.dependencies]
caps = "*"

[target.'cfg(target_family = "unix")'.dependencies]
jemallocator = "*"
jemalloc-ctl = "*"

[target.'cfg(windows)'.dependencies]
ctrlc = "*"
mio-named-pipes = "*"
mio = "*"
uuid = { version = "*", features = ["v4"] }
winapi =  { version = "*", features = ["namedpipeapi", "tlhelp32"] }

[dev-dependencies]
habitat_core = { path = "../core" }
hyper = "*"
json = "*"

[build-dependencies]
# Must use fork see https://github.com/habitat-sh/habitat/issues/7270
prost-build = { git = "https://github.com/dingelish/prost" }

[features]
default = []
apidocs = []
ignore_integration_tests = []
lock_as_rwlock = ["habitat_common/lock_as_rwlock"]
lock_as_mutex = ["habitat_common/lock_as_mutex"]
